name: Pizza Planet CI

on:
  pull_request:
    branches:
      - main

jobs:
  CI-Pizza-Planet:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.13"

      - name: Install Requirements
        run: pip3 install -r requirements.txt

      - name: Run tests
        run: python3 manage.py test

      - name: Build coverage file
        run: |
          pip install pytest-coverage
          pytest --cov=app --cov-report xml

      - name: Get Cover
        uses: orgoro/coverage@v3
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.SSH_TOKEN }}